name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout P1 repository
        uses: actions/checkout@v4
        with:
          repository: Aurquid/Terraform-vpc-p1
          path: p1

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::946509368278:role/GithubOIDC-TerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd p1/TFP1
          terraform init

      - name: Terraform Destroy
        run: |
          cd p1/TFP1
          terraform destroy -auto-approve
