name: Terraform CI/CD for Production VPC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout P3 Repo
        uses: actions/checkout@v4

      - name: Checkout Production VPC (P1) Repo
        uses: actions/checkout@v4
        with:
          repository: Aurquid/Terraform-Production-VPC-P1
          path: p1

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./p1
        run: terraform init

      - name: Terraform Format
        working-directory: ./p1
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./p1
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./p1
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./p1
        run: terraform apply -auto-approve tfplan
